### ISSUE TITLE
404 error when clicking "Start Migration"

### ISSUE THREAD

**Issue by intelligentspark** [isotope/migration#11]
Hi guys,

I've tried to use the migration tool in the following situaitons, and whenever I click "start migration", it immediately gives me a 404 error in all circumstances:

- subfolder of a site with a contao install in the root
- subdomain of a site with a contao install on the main domain

I thought the htaccess may have something to do with it, so I moved everything to a temp server, and the only thing that *doesn't* work is migration.  It is the default htaccess file being used from contao 3.5.12 in the root here:

http://173.239.8.253/~cvbdevco/migration/

and it still produces a 404 error.

**Comment by aschempp** [comment]
http://173.239.8.253/%7Ecvbdevco/migration/index.php/config/

You should use the phar file ;-)

**Comment by intelligentspark** [comment]
Thanks!
