### ISSUE TITLE
migration completed – but error message is shown at next database update

### ISSUE THREAD

**Issue by rustykowski** [isotope/migration#12]
Das Migrationstool hat seine Arbeit abgeschlossen, die Tabellen sind aktualisiert. Trotzdem erscheint bei weiteren Updates über die Erweiterungsverwaltung im letzten Schritt (Datenbank aktualisieren) eine Fehlermeldung mit dem Titel "Isotope eCommerce - Datenverlust-Absicherung".
Ist irgendwo vielleicht fälschlich noch ein Flag gesetzt?

![migration-error](https://cloud.githubusercontent.com/assets/1775048/20678816/7263f314-b598-11e6-9ad8-ae8ccd4a5361.png)

**Comment by aschempp** [comment]
Das ist kein Flag, sondern lediglich ein Prüfung der vorhandenen Tabellen. 

1. stelle sicher dass du die neuste Version des Tools hast, ich habe kürzlich einen entsprechenden Fehler behoben. 

2. Poste eine Liste deiner Datenbank-Tabellen welche mit tl_iso_ begonnen.

**Comment by rustykowski** [comment]
Zu 1: Das Tool müsste aktuell sein, habe ich vor 3 Tagen heruntergeladen. Das Dateidatum ist 31.08.

Zu 2: Hier alle Tabellennamen mit tl_iso...:
tl_iso_address
tl_iso_addresses
tl_iso_attribute
tl_iso_attribute_option
tl_iso_baseprice
tl_iso_config
tl_iso_document
tl_iso_download
tl_iso_gallery
tl_iso_group
tl_iso_label
tl_iso_orderstatus
tl_iso_payment
tl_iso_product
tl_iso_productcache
tl_iso_producttype
tl_iso_product_category
tl_iso_product_collection
tl_iso_product_collection_download
tl_iso_product_collection_item
tl_iso_product_collection_surcharge
tl_iso_product_price
tl_iso_product_pricetier
tl_iso_related_category
tl_iso_related_product
tl_iso_requestcache
tl_iso_rule
tl_iso_rule_restriction
tl_iso_rule_usage
tl_iso_shipping
tl_iso_tax_class
tl_iso_tax_rate

**Comment by aschempp** [comment]
Das Problem liegt an der Tabelle `tl_iso_addresses`, welche noch aus Isotope 1 stammt. Die Frage ist nun warum diese noch existiert. Prüfe folgendes:

 1. ist die Tabelle `tl_iso_addresses` leer?
 2. ist die Tabelle `tl_iso_address` leer?
 3. Falls nicht leer, enthalten sie dieselben Daten?

**Comment by rustykowski** [comment]
Guten Morgen Andreas,
`tl_iso_addresses` ist leer.
`tl_iso_address` ist mit ordentlichen Daten gefüllt.
adresses einfach löschen?

**Comment by aschempp** [comment]
Die Tabelle `tl_iso_addresses` löschen dürfte dein Problem beheben. 

Kannst du mir aber trotzdem noch weiterhelfen damit ich das Tool ggf. repariere kann? ;-)
Welche Werte gibt es im Feld `ptable` der Tabelle `tl_iso_address`? Kriegst du mit folgendem SQL:

```sql
SELECT DISTINCT ptable FROM tl_iso_address
```

**Comment by rustykowski** [comment]
Da gibts ausschließlich einen Wert: `tl_iso_product_collection`

**Comment by aschempp** [comment]
Perfekt, das habe ich erwartet. Deine Adresstabelle in Isotope 1 war leer, weil niemand das Adressbuch benutzt hat (vermutlich gab es das in deinem Shop nicht). In Isotope 2 werden auch die Adressen der Bestellungen in dieser Tabelle gespeichert, daher die Einträge mit `ptable` `tl_iso_product_collection`.

Ich vermute das Migrationstool behandelt die Adressen nicht korrekt wenn sie leer sind. Solche Fehler hatte ich schon mehrere, zuletzt wenn es keine E-Mail Benachrichtigungen gab trat dasselbe Problem auf… 😊

**Comment by rustykowski** [comment]
Richtig, es gab bislang keine Kundenregistrierung.
Das Datenbankupdate läuft nach dem Löschen der leeren Tabelle wieder problemlos.
Hast mir sehr geholfen, vielen Dank!

**Comment by aschempp** [comment]
Ich kann den Fehler leider nicht reproduzieren. Hast du eventuell noch ein Backup der alten Datenbank welche du mir per E-Mail (info@isotopeecommerce.org) senden könntest?
