### ISSUE TITLE
Fehler beim Ausführen des Migrationstools (config)

### ISSUE THREAD

**Issue by operatorone** [isotope/migration#9]
Nach Installtation des Migrationstools auf dem Server und aufrufen der Seite des Tools kommt nach dem Klicken auf "Migration starten" diese Meldung: The requested URL /migration/config was not found on this server.

Es existiert tatsächlich kein Ordner config in diesem Verzeichnis. Ich versuche eine 1.4.8 Isotope von einem 2.11.12 System auf eine 2.x Isotope in einer 3.4 upzudaten. Sollte dafür "Core only" an oder besser aus sein. Wenn es aus ist raucht nämlich das Backend ab und ich kann auf einer Fehlermeldung die mit IsotopeTranslation zusammen hängt nicht weitermachen.

**Comment by Toflar** [comment]
Das ist auch kein Ordner. Das ist einfach eine URL. Hast du denn `http(s)://deine-domain.tld/name-des-verzeichnisses/index.php/` aufgerufen oder hast du das `index.php` weggelassen?

**Comment by operatorone** [comment]
Arrrrrrg. Sorry, meine Blödheit. Hatte das index.php/ vergessen :(
Danke für den Tip. Ich probier es nochmal.
